apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apptest
  name: apptest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apptest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: apptest
    spec:
      containers:
      - readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 2
          httpGet:
            path:  /test.html
            port: 80
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 2
          httpGet:
            path: /test.html
            port: 80
        startupProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 15
          successThreshold: 1
          timeoutSeconds: 2
          tcpSocket:
            port: 80
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: apptest
        ports:
        - containerPort: 80
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5 
